#!/usr/bin/env bash

SYSTEMS=(
  darwin
  linux
  windows
)
ARCHITECTURES=(
  386
  amd64
)

echo "+ Prerequisites";
go get || exit 1;
echo "";

echo "+ Tests";
go vet || exit 2;
go test || exit 2;
echo "";

echo "+ Builds";
rm -rf dist; mkdir -p dist || exit 3;

numBuilds="$(("${#SYSTEMS[@]} * ${#ARCHITECTURES[@]}"))"
for GOOS in ${SYSTEMS[*]}; do
  EXTENSION=''
  [[ "$GOOS" == "windows" ]] && EXTENSION=".exe"

  printf "@ %s:\n" "$GOOS"

  for GOARCH in ${ARCHITECTURES[*]}; do
    export GOOS GOARCH;
    printf "[%d/%d]\t%s " "$((++buildNo))" "$numBuilds" "$GOARCH";
    go build -o dist/env-"$GOOS-$GOARCH""$EXTENSION" || exit 4;
    printf "✓\n";
  done

  echo "";
done
